version: '3.8'
services:
    front:
      container_name: front-container
      build:
        context: ./front
        dockerfile: ./Dockerfile.dev
      volumes:
        - ./front:/app
      ports:
        - 3000:3000
      # USED TO HOT RELOAD:
      environment:
        - CHOKIDAR_USEPOLLING=true
    api:
      container_name: api-container
      build:
        context: ./api
        dockerfile: ./Dockerfile.dev
      volumes:
        - ./api:/app
      ports:
        - 5000:5000
      environment:
        - FLASK_APP=main.py
        - FLASK_DEBUG=on