version: '3.8'
services:
    front:
      container_name: front-container
      build:
        context: ./front
        dockerfile: ./Dockerfile
      ports:
        - 80:80
    api:
      container_name: api-container
      build:
        context: ./api
        dockerfile: ./Dockerfile
      ports:
        - 5000:5000