FROM node:17-alpine

WORKDIR /app

COPY package.json .

# RUN: Commands to execute during build time
RUN npm install

COPY . .

EXPOSE 3000

# CMD: Commands to execute after build time, during running time
CMD ["npm", "run", "dev"]